### ISSUE TITLE
Join AEP - but why ? 

### ISSUE THREAD

**Issue by victorjunlu** [aep-dev/site-generator-orig#17]
Many Open Source projects typically adhere to an established "API standard." The question arises as to the rationale behind individuals joining the AEP to assess their current standards, considering that there may not be a definitive answer, and best practices are subject to evolution, lacking a fixed nature.

**Comment by toumorokoshi** [comment]
closing as a dupe of https://github.com/aep-dev/aep.dev/issues/86
